/**
 * Squad seed generator. Writes src/data/squads.ts from researched rosters.
 * Prefers .research/squads-2026.json (full rosters from the squad-research
 * workflow); falls back to .research/stars.json (curated subset) so the app
 * compiles before the research lands. Rosters are STATIC public info — never
 * fetched from the live API. Run: node scripts/build-squads.mjs
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const R = (f) => JSON.parse(fs.readFileSync(path.join(ROOT, '.research', f), 'utf8'))

const POS = (s) => {
  const u = (s || '').toUpperCase()
  if (u.startsWith('G')) return 'GK'
  if (u.startsWith('D') || u.includes('BACK')) return 'DF'
  if (u.startsWith('M')) return 'MF'
  return 'FW'
}

const SQUADS = {}
let source = ''

if (fs.existsSync(path.join(ROOT, '.research', 'squads-2026.json'))) {
  source = 'squads-2026.json (full rosters)'
  const data = R('squads-2026.json') // array of { code, players:[{name,position,club,number}], verified }
  for (const t of data) {
    const players = (t.players || [])
      .filter((p) => p && p.name)
      .map((p) => ({
        name: p.name,
        position: POS(p.position),
        number: p.number ?? null,
        ...(p.club ? { club: p.club } : {}),
      }))
    SQUADS[t.code] = { players, verified: Boolean(t.verified) && players.length >= 18 }
  }
} else {
  source = 'stars.json (curated fallback — rosters NOT yet researched)'
  const stars = R('stars.json') // { teams:[{code, star, notableSquad}] }
  for (const t of stars.teams) {
    const all = [t.star, ...(t.notableSquad || [])].filter(Boolean)
    SQUADS[t.code] = {
      players: all.map((p) => ({ name: p.name, position: POS(p.position), number: p.number ?? null, ...(p.club ? { club: p.club } : {}) })),
      verified: false,
    }
  }
}

const banner = `/**\n * AUTO-GENERATED by scripts/build-squads.mjs — do not edit by hand.\n * Static public squad rosters (NOT from the live API). Source: ${source}.\n */\n`
const body = `${banner}import type { TeamSquad } from '@/domain/types'\n\nexport const SQUADS: Record<string, TeamSquad> = ${JSON.stringify(SQUADS, null, 2)}\n`
fs.writeFileSync(path.join(ROOT, 'src', 'data', 'squads.ts'), body)

const codes = Object.keys(SQUADS)
const total = codes.reduce((a, c) => a + SQUADS[c].players.length, 0)
const unverified = codes.filter((c) => !SQUADS[c].verified)
console.log(`Wrote src/data/squads.ts from ${source}`)
console.log(`  ${codes.length} teams · ${total} players · avg ${(total / codes.length).toFixed(1)}/team`)
console.log(`  unverified teams (${unverified.length}): ${unverified.join(', ') || 'none'}`)
