/**
 * Fetch REAL group-stage box scores from ESPN's free, no-key public API and emit
 * src/data/teamStats.ts. The radar (ability card) reads this statically — so the
 * group stage needs zero API key and zero quota. Re-run after the group stage
 * finishes (and could be extended to knockouts) with: node scripts/fetch-espn.mjs
 *
 * ESPN endpoints (no auth):
 *   /scoreboard?dates=YYYYMMDD   -> that day's matches + event ids + status
 *   /summary?event=ID            -> boxscore.teams[].statistics (per-team stats)
 *
 * No xG / xA / key passes on ESPN, so Creativity stays null (never fabricated).
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const BASE = 'https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world'

/* ESPN team name -> our 3-letter code, built from the seed teams + a few aliases. */
const teamsTs = fs.readFileSync(path.join(ROOT, 'src/data/teams.ts'), 'utf8')
const TEAMS = JSON.parse(teamsTs.split('export const TEAMS: Team[] = ')[1].split('\n\nexport const teamByCode')[0])
const fold = (s) => (s || '').normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[’'`]/g, '').toLowerCase().trim()
const NAME2CODE = {}
for (const t of TEAMS) NAME2CODE[fold(t.name)] = t.code
const ALIAS = {
  'ivory coast': 'CIV', 'cote divoire': 'CIV', turkiye: 'TUR', turkey: 'TUR', 'south korea': 'KOR',
  'korea republic': 'KOR', usa: 'USA', 'united states': 'USA', iran: 'IRN', 'ir iran': 'IRN',
  'cape verde': 'CPV', 'cabo verde': 'CPV', curacao: 'CUW', 'dr congo': 'COD', 'congo dr': 'COD',
  czechia: 'CZE', 'czech republic': 'CZE', 'saudi arabia': 'KSA', 'bosnia and herzegovina': 'BIH',
  'bosnia-herzegovina': 'BIH', 'bosnia & herzegovina': 'BIH', bosnia: 'BIH', 'south africa': 'RSA',
}
const codeFor = (name) => NAME2CODE[fold(name)] ?? ALIAS[fold(name)] ?? null

const getJson = async (url) => {
  const r = await fetch(url, { headers: { 'user-agent': 'Mozilla/5.0' } })
  if (!r.ok) throw new Error(`${url} -> HTTP ${r.status}`)
  return r.json()
}
const statVal = (team, name) => {
  const s = (team.statistics || []).find((x) => x.name === name)
  if (!s) return null
  const v = typeof s.value === 'number' ? s.value : parseFloat(s.displayValue)
  return Number.isFinite(v) ? v : null
}

const dates = []
for (let d = 11; d <= 27; d++) dates.push(`202606${String(d).padStart(2, '0')}`) // pure group-stage window

const unmatched = new Set()
const GROUP_STATS = {}
let matches = 0

for (const dt of dates) {
  let sb
  try { sb = await getJson(`${BASE}/scoreboard?dates=${dt}`) } catch (e) { console.warn('scoreboard', dt, e.message); continue }
  for (const e of sb.events || []) {
    const c = e.competitions?.[0]
    if (!c || c.status?.type?.state !== 'post') continue // finished only
    const headline = c.notes?.[0]?.headline || ''
    if (headline && !/group/i.test(headline)) continue // skip any non-group fixture
    const home = c.competitors.find((x) => x.homeAway === 'home')
    const away = c.competitors.find((x) => x.homeAway === 'away')
    const hCode = codeFor(home?.team?.displayName)
    const aCode = codeFor(away?.team?.displayName)
    if (!hCode) unmatched.add(home?.team?.displayName)
    if (!aCode) unmatched.add(away?.team?.displayName)
    if (!hCode || !aCode) continue
    const hs = Number(home.score), as = Number(away.score)

    let sum
    try { sum = await getJson(`${BASE}/summary?event=${e.id}`) } catch (err) { console.warn('summary', e.id, err.message); continue }
    const bt = sum.boxscore?.teams || []
    if (bt.length < 2) continue

    for (const t of bt) {
      const code = codeFor(t.team?.displayName)
      if (!code) { unmatched.add(t.team?.displayName); continue }
      const isHome = code === hCode
      const gf = isHome ? hs : as
      const ga = isHome ? as : hs
      const poss = statVal(t, 'possessionPct')
      ;(GROUP_STATS[code] ||= []).push({
        code,
        goalsFor: gf,
        goalsAgainst: ga,
        cleanSheet: ga === 0,
        possession: poss == null ? null : Math.round(poss),
        shots: statVal(t, 'totalShots'),
        shotsOnTarget: statVal(t, 'shotsOnTarget'),
        passPct: statVal(t, 'passPct'),
        crosses: statVal(t, 'accurateCrosses'),
        corners: statVal(t, 'wonCorners'),
        tackles: statVal(t, 'effectiveTackles'),
        interceptions: statVal(t, 'interceptions'),
        clearances: statVal(t, 'effectiveClearance'),
        fouls: statVal(t, 'foulsCommitted'),
        yellow: statVal(t, 'yellowCards'),
        red: statVal(t, 'redCards'),
        gkSaves: statVal(t, 'saves'),
      })
    }
    matches++
  }
}

const asOf = new Date().toISOString().slice(0, 10)
const banner = `/**\n * AUTO-GENERATED by scripts/fetch-espn.mjs — REAL group-stage box scores from\n * ESPN's free public API (no key, no quota). As of ${asOf}. Re-run to refresh.\n * Creativity (xA / key passes) is null — ESPN doesn't expose it; never fabricated.\n */\n`
fs.writeFileSync(
  path.join(ROOT, 'src/data/teamStats.ts'),
  `${banner}import type { TeamMatchStats } from '@/lib/api'\n\nexport const GROUP_STATS: Record<string, TeamMatchStats[]> = ${JSON.stringify(GROUP_STATS, null, 2)}\n`,
)

console.log(`Wrote src/data/teamStats.ts — ${matches} matches, ${Object.keys(GROUP_STATS).length} teams.`)
if (unmatched.size) console.warn('UNMATCHED ESPN names (fix the alias map):', [...unmatched].join(', '))
