/**
 * AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.
 * Verified 2026 World Cup snapshot as of 2026-06-25.
 */
import type { BracketMatch } from '@/domain/types'

export const BRACKET: BracketMatch[] = [
  {
    "matchNo": 73,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "runnerUp",
        "group": "A"
      },
      "label": "Runner-up A"
    },
    "away": {
      "source": {
        "kind": "runnerUp",
        "group": "B"
      },
      "label": "Runner-up B"
    },
    "kickoff": "2026-06-28T19:00:00Z",
    "venue": "SoFi Stadium",
    "city": "Inglewood (Los Angeles)"
  },
  {
    "matchNo": 74,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "E"
      },
      "label": "Winner E"
    },
    "away": {
      "source": {
        "kind": "third",
        "groups": [
          "A",
          "B",
          "C",
          "D",
          "F"
        ]
      },
      "label": "3rd A/B/C/D/F"
    },
    "kickoff": "2026-06-29T20:30:00Z",
    "venue": "Gillette Stadium",
    "city": "Foxborough (Boston)"
  },
  {
    "matchNo": 75,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "F"
      },
      "label": "Winner F"
    },
    "away": {
      "source": {
        "kind": "runnerUp",
        "group": "C"
      },
      "label": "Runner-up C"
    },
    "kickoff": "2026-06-30T01:00:00Z",
    "venue": "Estadio BBVA",
    "city": "Guadalupe (Monterrey)"
  },
  {
    "matchNo": 76,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "C"
      },
      "label": "Winner C"
    },
    "away": {
      "source": {
        "kind": "runnerUp",
        "group": "F"
      },
      "label": "Runner-up F"
    },
    "kickoff": "2026-06-29T17:00:00Z",
    "venue": "NRG Stadium",
    "city": "Houston"
  },
  {
    "matchNo": 77,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "I"
      },
      "label": "Winner I"
    },
    "away": {
      "source": {
        "kind": "third",
        "groups": [
          "C",
          "D",
          "F",
          "G",
          "H"
        ]
      },
      "label": "3rd C/D/F/G/H"
    },
    "kickoff": "2026-06-30T21:00:00Z",
    "venue": "MetLife Stadium",
    "city": "East Rutherford (New York/New Jersey)"
  },
  {
    "matchNo": 78,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "runnerUp",
        "group": "E"
      },
      "label": "Runner-up E"
    },
    "away": {
      "source": {
        "kind": "runnerUp",
        "group": "I"
      },
      "label": "Runner-up I"
    },
    "kickoff": "2026-06-30T17:00:00Z",
    "venue": "AT&T Stadium",
    "city": "Arlington (Dallas)"
  },
  {
    "matchNo": 79,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "A"
      },
      "label": "Winner A"
    },
    "away": {
      "source": {
        "kind": "third",
        "groups": [
          "C",
          "E",
          "F",
          "H",
          "I"
        ]
      },
      "label": "3rd C/E/F/H/I"
    },
    "kickoff": "2026-07-01T01:00:00Z",
    "venue": "Estadio Azteca",
    "city": "Mexico City"
  },
  {
    "matchNo": 80,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "L"
      },
      "label": "Winner L"
    },
    "away": {
      "source": {
        "kind": "third",
        "groups": [
          "E",
          "H",
          "I",
          "J",
          "K"
        ]
      },
      "label": "3rd E/H/I/J/K"
    },
    "kickoff": "2026-07-01T16:00:00Z",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta"
  },
  {
    "matchNo": 81,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "D"
      },
      "label": "Winner D"
    },
    "away": {
      "source": {
        "kind": "third",
        "groups": [
          "B",
          "E",
          "F",
          "I",
          "J"
        ]
      },
      "label": "3rd B/E/F/I/J"
    },
    "kickoff": "2026-07-02T00:00:00Z",
    "venue": "Levi's Stadium",
    "city": "Santa Clara (San Francisco Bay Area)"
  },
  {
    "matchNo": 82,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "G"
      },
      "label": "Winner G"
    },
    "away": {
      "source": {
        "kind": "third",
        "groups": [
          "A",
          "E",
          "H",
          "I",
          "J"
        ]
      },
      "label": "3rd A/E/H/I/J"
    },
    "kickoff": "2026-07-01T20:00:00Z",
    "venue": "Lumen Field",
    "city": "Seattle"
  },
  {
    "matchNo": 83,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "runnerUp",
        "group": "K"
      },
      "label": "Runner-up K"
    },
    "away": {
      "source": {
        "kind": "runnerUp",
        "group": "L"
      },
      "label": "Runner-up L"
    },
    "kickoff": "2026-07-02T23:00:00Z",
    "venue": "BMO Field",
    "city": "Toronto"
  },
  {
    "matchNo": 84,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "H"
      },
      "label": "Winner H"
    },
    "away": {
      "source": {
        "kind": "runnerUp",
        "group": "J"
      },
      "label": "Runner-up J"
    },
    "kickoff": "2026-07-02T19:00:00Z",
    "venue": "SoFi Stadium",
    "city": "Inglewood (Los Angeles)"
  },
  {
    "matchNo": 85,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "B"
      },
      "label": "Winner B"
    },
    "away": {
      "source": {
        "kind": "third",
        "groups": [
          "E",
          "F",
          "G",
          "I",
          "J"
        ]
      },
      "label": "3rd E/F/G/I/J"
    },
    "kickoff": "2026-07-03T03:00:00Z",
    "venue": "BC Place",
    "city": "Vancouver"
  },
  {
    "matchNo": 86,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "J"
      },
      "label": "Winner J"
    },
    "away": {
      "source": {
        "kind": "runnerUp",
        "group": "H"
      },
      "label": "Runner-up H"
    },
    "kickoff": "2026-07-03T22:00:00Z",
    "venue": "Hard Rock Stadium",
    "city": "Miami Gardens"
  },
  {
    "matchNo": 87,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "winner",
        "group": "K"
      },
      "label": "Winner K"
    },
    "away": {
      "source": {
        "kind": "third",
        "groups": [
          "D",
          "E",
          "I",
          "J",
          "L"
        ]
      },
      "label": "3rd D/E/I/J/L"
    },
    "kickoff": "2026-07-04T01:30:00Z",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City"
  },
  {
    "matchNo": 88,
    "stage": "R32",
    "home": {
      "source": {
        "kind": "runnerUp",
        "group": "D"
      },
      "label": "Runner-up D"
    },
    "away": {
      "source": {
        "kind": "runnerUp",
        "group": "G"
      },
      "label": "Runner-up G"
    },
    "kickoff": "2026-07-03T18:00:00Z",
    "venue": "AT&T Stadium",
    "city": "Arlington (Dallas)"
  },
  {
    "matchNo": 89,
    "stage": "R16",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 74
      },
      "label": "Winner M74"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 77
      },
      "label": "Winner M77"
    },
    "kickoff": "2026-07-04T18:00:00Z",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia"
  },
  {
    "matchNo": 90,
    "stage": "R16",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 73
      },
      "label": "Winner M73"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 75
      },
      "label": "Winner M75"
    },
    "kickoff": "2026-07-04T18:00:00Z",
    "venue": "NRG Stadium",
    "city": "Houston"
  },
  {
    "matchNo": 91,
    "stage": "R16",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 76
      },
      "label": "Winner M76"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 78
      },
      "label": "Winner M78"
    },
    "kickoff": "2026-07-05T18:00:00Z",
    "venue": "MetLife Stadium",
    "city": "East Rutherford"
  },
  {
    "matchNo": 92,
    "stage": "R16",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 79
      },
      "label": "Winner M79"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 80
      },
      "label": "Winner M80"
    },
    "kickoff": "2026-07-05T18:00:00Z",
    "venue": "Estadio Azteca",
    "city": "Mexico City"
  },
  {
    "matchNo": 93,
    "stage": "R16",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 83
      },
      "label": "Winner M83"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 84
      },
      "label": "Winner M84"
    },
    "kickoff": "2026-07-06T18:00:00Z",
    "venue": "AT&T Stadium",
    "city": "Arlington"
  },
  {
    "matchNo": 94,
    "stage": "R16",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 81
      },
      "label": "Winner M81"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 82
      },
      "label": "Winner M82"
    },
    "kickoff": "2026-07-06T18:00:00Z",
    "venue": "Lumen Field",
    "city": "Seattle"
  },
  {
    "matchNo": 95,
    "stage": "R16",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 86
      },
      "label": "Winner M86"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 88
      },
      "label": "Winner M88"
    },
    "kickoff": "2026-07-07T18:00:00Z",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta"
  },
  {
    "matchNo": 96,
    "stage": "R16",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 85
      },
      "label": "Winner M85"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 87
      },
      "label": "Winner M87"
    },
    "kickoff": "2026-07-07T18:00:00Z",
    "venue": "BC Place",
    "city": "Vancouver"
  },
  {
    "matchNo": 97,
    "stage": "QF",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 89
      },
      "label": "Winner M89"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 90
      },
      "label": "Winner M90"
    },
    "kickoff": "2026-07-09T18:00:00Z",
    "venue": "Gillette Stadium",
    "city": "Foxborough"
  },
  {
    "matchNo": 98,
    "stage": "QF",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 93
      },
      "label": "Winner M93"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 94
      },
      "label": "Winner M94"
    },
    "kickoff": "2026-07-10T18:00:00Z",
    "venue": "SoFi Stadium",
    "city": "Inglewood"
  },
  {
    "matchNo": 99,
    "stage": "QF",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 91
      },
      "label": "Winner M91"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 92
      },
      "label": "Winner M92"
    },
    "kickoff": "2026-07-11T18:00:00Z",
    "venue": "Hard Rock Stadium",
    "city": "Miami Gardens"
  },
  {
    "matchNo": 100,
    "stage": "QF",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 95
      },
      "label": "Winner M95"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 96
      },
      "label": "Winner M96"
    },
    "kickoff": "2026-07-11T18:00:00Z",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City"
  },
  {
    "matchNo": 101,
    "stage": "SF",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 97
      },
      "label": "Winner M97"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 98
      },
      "label": "Winner M98"
    },
    "kickoff": "2026-07-14T18:00:00Z",
    "venue": "AT&T Stadium",
    "city": "Arlington"
  },
  {
    "matchNo": 102,
    "stage": "SF",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 99
      },
      "label": "Winner M99"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 100
      },
      "label": "Winner M100"
    },
    "kickoff": "2026-07-15T18:00:00Z",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta"
  },
  {
    "matchNo": 103,
    "stage": "F3",
    "home": {
      "source": {
        "kind": "matchLoser",
        "matchNo": 101
      },
      "label": "Loser M101"
    },
    "away": {
      "source": {
        "kind": "matchLoser",
        "matchNo": 102
      },
      "label": "Loser M102"
    },
    "kickoff": "2026-07-18T18:00:00Z",
    "venue": "Hard Rock Stadium",
    "city": "Miami Gardens"
  },
  {
    "matchNo": 104,
    "stage": "F",
    "home": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 101
      },
      "label": "Winner M101"
    },
    "away": {
      "source": {
        "kind": "matchWinner",
        "matchNo": 102
      },
      "label": "Winner M102"
    },
    "kickoff": "2026-07-19T18:00:00Z",
    "venue": "MetLife Stadium",
    "city": "East Rutherford"
  }
]
