/**
 * AUTO-GENERATED by scripts/build-squads.mjs — do not edit by hand.
 * Static public squad rosters (NOT from the live API). Source: stars.json (curated fallback — rosters NOT yet researched).
 */
import type { TeamSquad } from '@/domain/types'

export const SQUADS: Record<string, TeamSquad> = {
  "ARG": {
    "players": [
      {
        "name": "Lionel Messi",
        "position": "FW",
        "number": 10,
        "club": "Inter Miami"
      },
      {
        "name": "Lautaro Martínez",
        "position": "FW",
        "number": 22,
        "club": "Inter Milan"
      },
      {
        "name": "Julián Álvarez",
        "position": "FW",
        "number": 9,
        "club": "Atlético Madrid"
      },
      {
        "name": "Emiliano Martínez",
        "position": "GK",
        "number": 23,
        "club": "Aston Villa"
      },
      {
        "name": "Enzo Fernández",
        "position": "MF",
        "number": 24,
        "club": "Chelsea"
      },
      {
        "name": "Alexis Mac Allister",
        "position": "MF",
        "number": 20,
        "club": "Liverpool"
      },
      {
        "name": "Cristian Romero",
        "position": "DF",
        "number": 13,
        "club": "Tottenham Hotspur"
      }
    ],
    "verified": false
  },
  "FRA": {
    "players": [
      {
        "name": "Kylian Mbappé",
        "position": "FW",
        "number": 10,
        "club": "Real Madrid"
      },
      {
        "name": "Ousmane Dembélé",
        "position": "FW",
        "number": null,
        "club": "Paris Saint-Germain"
      },
      {
        "name": "Michael Olise",
        "position": "FW",
        "number": null,
        "club": "Bayern Munich"
      },
      {
        "name": "Aurélien Tchouaméni",
        "position": "MF",
        "number": null,
        "club": "Real Madrid"
      },
      {
        "name": "William Saliba",
        "position": "DF",
        "number": null,
        "club": "Arsenal"
      },
      {
        "name": "Mike Maignan",
        "position": "GK",
        "number": null,
        "club": "AC Milan"
      },
      {
        "name": "Désiré Doué",
        "position": "FW",
        "number": null,
        "club": "Paris Saint-Germain"
      }
    ],
    "verified": false
  },
  "BRA": {
    "players": [
      {
        "name": "Vinícius Júnior",
        "position": "FW",
        "number": null,
        "club": "Real Madrid"
      },
      {
        "name": "Raphinha",
        "position": "FW",
        "number": null,
        "club": "Barcelona"
      },
      {
        "name": "Neymar",
        "position": "FW",
        "number": null,
        "club": "Santos"
      },
      {
        "name": "Alisson",
        "position": "GK",
        "number": null,
        "club": "Liverpool"
      },
      {
        "name": "Marquinhos",
        "position": "DF",
        "number": null,
        "club": "Paris Saint-Germain"
      },
      {
        "name": "Bruno Guimarães",
        "position": "MF",
        "number": null,
        "club": "Newcastle United"
      },
      {
        "name": "Casemiro",
        "position": "MF",
        "number": null,
        "club": "Manchester United"
      }
    ],
    "verified": false
  },
  "ESP": {
    "players": [
      {
        "name": "Lamine Yamal",
        "position": "FW",
        "number": null,
        "club": "Barcelona"
      },
      {
        "name": "Pedri",
        "position": "MF",
        "number": null,
        "club": "Barcelona"
      },
      {
        "name": "Rodri",
        "position": "MF",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "Mikel Oyarzabal",
        "position": "FW",
        "number": null,
        "club": "Real Sociedad"
      },
      {
        "name": "Marc Cucurella",
        "position": "DF",
        "number": null,
        "club": "Chelsea"
      },
      {
        "name": "Nico Williams",
        "position": "FW",
        "number": null,
        "club": "Athletic Bilbao"
      },
      {
        "name": "Pau Cubarsí",
        "position": "DF",
        "number": null,
        "club": "Barcelona"
      }
    ],
    "verified": false
  },
  "ENG": {
    "players": [
      {
        "name": "Harry Kane",
        "position": "FW",
        "number": null,
        "club": "Bayern Munich"
      },
      {
        "name": "Jude Bellingham",
        "position": "MF",
        "number": null,
        "club": "Real Madrid"
      },
      {
        "name": "Bukayo Saka",
        "position": "FW",
        "number": null,
        "club": "Arsenal"
      },
      {
        "name": "Declan Rice",
        "position": "MF",
        "number": null,
        "club": "Arsenal"
      },
      {
        "name": "Jordan Pickford",
        "position": "GK",
        "number": null,
        "club": "Everton"
      },
      {
        "name": "Marc Guéhi",
        "position": "DF",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "John Stones",
        "position": "DF",
        "number": null,
        "club": "Manchester City"
      }
    ],
    "verified": false
  },
  "POR": {
    "players": [
      {
        "name": "Cristiano Ronaldo",
        "position": "FW",
        "number": 7,
        "club": "Al Nassr"
      },
      {
        "name": "Bruno Fernandes",
        "position": "MF",
        "number": null,
        "club": "Manchester United"
      },
      {
        "name": "Vitinha",
        "position": "MF",
        "number": null,
        "club": "Paris Saint-Germain"
      },
      {
        "name": "Rúben Dias",
        "position": "DF",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "Bernardo Silva",
        "position": "MF",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "Rafael Leão",
        "position": "FW",
        "number": null,
        "club": "AC Milan"
      },
      {
        "name": "Nuno Mendes",
        "position": "DF",
        "number": null,
        "club": "Paris Saint-Germain"
      }
    ],
    "verified": false
  },
  "GER": {
    "players": [
      {
        "name": "Florian Wirtz",
        "position": "MF",
        "number": null,
        "club": "Liverpool"
      },
      {
        "name": "Joshua Kimmich",
        "position": "DF",
        "number": null,
        "club": "Bayern Munich"
      },
      {
        "name": "Antonio Rüdiger",
        "position": "DF",
        "number": null,
        "club": "Real Madrid"
      },
      {
        "name": "Manuel Neuer",
        "position": "GK",
        "number": null,
        "club": "Bayern Munich"
      },
      {
        "name": "Kai Havertz",
        "position": "FW",
        "number": null,
        "club": "Arsenal"
      },
      {
        "name": "Jamal Musiala",
        "position": "MF",
        "number": null,
        "club": "Bayern Munich"
      }
    ],
    "verified": false
  },
  "NED": {
    "players": [
      {
        "name": "Virgil van Dijk",
        "position": "DF",
        "number": 4,
        "club": "Liverpool"
      },
      {
        "name": "Frenkie de Jong",
        "position": "MF",
        "number": null,
        "club": "Barcelona"
      },
      {
        "name": "Cody Gakpo",
        "position": "FW",
        "number": null,
        "club": "Liverpool"
      },
      {
        "name": "Memphis Depay",
        "position": "FW",
        "number": null,
        "club": "Corinthians"
      },
      {
        "name": "Denzel Dumfries",
        "position": "DF",
        "number": null,
        "club": "Inter Milan"
      },
      {
        "name": "Tijjani Reijnders",
        "position": "MF",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "Donyell Malen",
        "position": "FW",
        "number": null,
        "club": "Roma"
      }
    ],
    "verified": false
  },
  "BEL": {
    "players": [
      {
        "name": "Kevin De Bruyne",
        "position": "MF",
        "number": null,
        "club": "Napoli"
      },
      {
        "name": "Jeremy Doku",
        "position": "FW",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "Romelu Lukaku",
        "position": "FW",
        "number": null,
        "club": "Napoli"
      },
      {
        "name": "Thibaut Courtois",
        "position": "GK",
        "number": null,
        "club": "Real Madrid"
      },
      {
        "name": "Youri Tielemans",
        "position": "MF",
        "number": null,
        "club": "Aston Villa"
      },
      {
        "name": "Leandro Trossard",
        "position": "FW",
        "number": null,
        "club": "Arsenal"
      }
    ],
    "verified": false
  },
  "USA": {
    "players": [
      {
        "name": "Christian Pulisic",
        "position": "FW",
        "number": null,
        "club": "AC Milan"
      },
      {
        "name": "Weston McKennie",
        "position": "MF",
        "number": null,
        "club": "Juventus"
      },
      {
        "name": "Tyler Adams",
        "position": "MF",
        "number": null,
        "club": "AFC Bournemouth"
      },
      {
        "name": "Folarin Balogun",
        "position": "FW",
        "number": null,
        "club": "AS Monaco"
      },
      {
        "name": "Tim Weah",
        "position": "FW",
        "number": null,
        "club": "Marseille"
      },
      {
        "name": "Gio Reyna",
        "position": "MF",
        "number": null,
        "club": "Borussia Mönchengladbach"
      },
      {
        "name": "Ricardo Pepi",
        "position": "FW",
        "number": null,
        "club": "PSV Eindhoven"
      }
    ],
    "verified": false
  },
  "MEX": {
    "players": [
      {
        "name": "Edson Álvarez",
        "position": "DF",
        "number": 4,
        "club": "Fenerbahçe"
      },
      {
        "name": "Santiago Giménez",
        "position": "FW",
        "number": 11,
        "club": "AC Milan"
      },
      {
        "name": "Raúl Jiménez",
        "position": "FW",
        "number": 9,
        "club": "Fulham"
      },
      {
        "name": "Guillermo Ochoa",
        "position": "GK",
        "number": 13,
        "club": "AEL Limassol"
      },
      {
        "name": "Johan Vásquez",
        "position": "DF",
        "number": 5,
        "club": "Genoa"
      },
      {
        "name": "Orbelín Pineda",
        "position": "MF",
        "number": 17,
        "club": "AEK Athens"
      },
      {
        "name": "Gilberto Mora",
        "position": "MF",
        "number": 19,
        "club": "Tijuana"
      }
    ],
    "verified": false
  },
  "CAN": {
    "players": [
      {
        "name": "Alphonso Davies",
        "position": "DF",
        "number": 19,
        "club": "Bayern Munich"
      },
      {
        "name": "Jonathan David",
        "position": "FW",
        "number": 10,
        "club": "Juventus"
      },
      {
        "name": "Stephen Eustáquio",
        "position": "MF",
        "number": 7,
        "club": "Los Angeles FC"
      },
      {
        "name": "Cyle Larin",
        "position": "FW",
        "number": 9,
        "club": "Southampton"
      },
      {
        "name": "Alistair Johnston",
        "position": "DF",
        "number": 2,
        "club": "Celtic"
      },
      {
        "name": "Ismaël Koné",
        "position": "MF",
        "number": 8,
        "club": "Sassuolo"
      },
      {
        "name": "Dayne St. Clair",
        "position": "GK",
        "number": 1,
        "club": "Inter Miami"
      }
    ],
    "verified": false
  },
  "CRO": {
    "players": [
      {
        "name": "Luka Modrić",
        "position": "MF",
        "number": 10,
        "club": "AC Milan"
      },
      {
        "name": "Joško Gvardiol",
        "position": "DF",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "Mateo Kovačić",
        "position": "MF",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "Andrej Kramarić",
        "position": "FW",
        "number": null,
        "club": "Hoffenheim"
      },
      {
        "name": "Ivan Perišić",
        "position": "FW",
        "number": null,
        "club": "PSV Eindhoven"
      },
      {
        "name": "Mario Pašalić",
        "position": "MF",
        "number": null,
        "club": "Atalanta"
      }
    ],
    "verified": false
  },
  "URU": {
    "players": [
      {
        "name": "Federico Valverde",
        "position": "MF",
        "number": null,
        "club": "Real Madrid"
      },
      {
        "name": "Darwin Núñez",
        "position": "FW",
        "number": null,
        "club": "Liverpool"
      },
      {
        "name": "Ronald Araújo",
        "position": "DF",
        "number": null,
        "club": "Barcelona"
      },
      {
        "name": "Rodrigo Bentancur",
        "position": "MF",
        "number": null,
        "club": "Tottenham Hotspur"
      },
      {
        "name": "Manuel Ugarte",
        "position": "MF",
        "number": null,
        "club": "Manchester United"
      },
      {
        "name": "José María Giménez",
        "position": "DF",
        "number": null,
        "club": "Atlético Madrid"
      },
      {
        "name": "Fernando Muslera",
        "position": "GK",
        "number": null,
        "club": "Galatasaray"
      }
    ],
    "verified": false
  },
  "COL": {
    "players": [
      {
        "name": "Luis Díaz",
        "position": "FW",
        "number": null,
        "club": "Bayern Munich"
      },
      {
        "name": "James Rodríguez",
        "position": "MF",
        "number": 10,
        "club": "Club León"
      },
      {
        "name": "David Ospina",
        "position": "GK",
        "number": 1,
        "club": "Atlético Nacional"
      },
      {
        "name": "Jhon Durán",
        "position": "FW",
        "number": null,
        "club": "Al-Nassr"
      },
      {
        "name": "Daniel Muñoz",
        "position": "DF",
        "number": null,
        "club": "Crystal Palace"
      },
      {
        "name": "Richard Ríos",
        "position": "MF",
        "number": null,
        "club": "Benfica"
      }
    ],
    "verified": false
  },
  "ECU": {
    "players": [
      {
        "name": "Moisés Caicedo",
        "position": "MF",
        "number": null,
        "club": "Chelsea"
      },
      {
        "name": "Enner Valencia",
        "position": "FW",
        "number": null,
        "club": "Internacional"
      },
      {
        "name": "Piero Hincapié",
        "position": "DF",
        "number": null,
        "club": "Arsenal"
      },
      {
        "name": "Willian Pacho",
        "position": "DF",
        "number": null,
        "club": "Paris Saint-Germain"
      },
      {
        "name": "Pervis Estupiñán",
        "position": "DF",
        "number": null,
        "club": "AC Milan"
      },
      {
        "name": "Gonzalo Plata",
        "position": "FW",
        "number": null,
        "club": "Flamengo"
      },
      {
        "name": "Kendry Páez",
        "position": "MF",
        "number": null,
        "club": "Chelsea"
      }
    ],
    "verified": false
  },
  "PAR": {
    "players": [
      {
        "name": "Miguel Almirón",
        "position": "MF",
        "number": null,
        "club": "Atlanta United"
      },
      {
        "name": "Antonio Sanabria",
        "position": "FW",
        "number": null,
        "club": "Torino"
      },
      {
        "name": "Julio Enciso",
        "position": "FW",
        "number": null,
        "club": "Brighton & Hove Albion"
      },
      {
        "name": "Diego Gómez",
        "position": "MF",
        "number": null,
        "club": "Brighton & Hove Albion"
      },
      {
        "name": "Omar Alderete",
        "position": "DF",
        "number": null,
        "club": "Sunderland"
      },
      {
        "name": "Gustavo Gómez",
        "position": "DF",
        "number": null,
        "club": "Palmeiras"
      }
    ],
    "verified": false
  },
  "MAR": {
    "players": [
      {
        "name": "Achraf Hakimi",
        "position": "DF",
        "number": 2,
        "club": "Paris Saint-Germain"
      },
      {
        "name": "Brahim Díaz",
        "position": "FW",
        "number": null,
        "club": "Real Madrid"
      },
      {
        "name": "Noussair Mazraoui",
        "position": "DF",
        "number": null,
        "club": "Manchester United"
      },
      {
        "name": "Nayef Aguerd",
        "position": "DF",
        "number": null,
        "club": "Marseille"
      },
      {
        "name": "Sofyan Amrabat",
        "position": "MF",
        "number": null,
        "club": "Real Betis"
      },
      {
        "name": "Bilal El Khannouss",
        "position": "MF",
        "number": null,
        "club": "Stuttgart"
      },
      {
        "name": "Ayoub El Kaabi",
        "position": "FW",
        "number": null,
        "club": "Olympiacos"
      }
    ],
    "verified": false
  },
  "SEN": {
    "players": [
      {
        "name": "Sadio Mané",
        "position": "FW",
        "number": 10,
        "club": "Al Nassr"
      },
      {
        "name": "Kalidou Koulibaly",
        "position": "DF",
        "number": null,
        "club": "Al-Hilal"
      },
      {
        "name": "Nicolas Jackson",
        "position": "FW",
        "number": null,
        "club": "Bayern Munich"
      },
      {
        "name": "Ismaïla Sarr",
        "position": "FW",
        "number": null,
        "club": "Crystal Palace"
      },
      {
        "name": "Idrissa Gana Gueye",
        "position": "MF",
        "number": null,
        "club": "Everton"
      },
      {
        "name": "Édouard Mendy",
        "position": "GK",
        "number": null,
        "club": "Al-Ahli"
      }
    ],
    "verified": false
  },
  "CIV": {
    "players": [
      {
        "name": "Simon Adingra",
        "position": "FW",
        "number": null,
        "club": "Monaco"
      },
      {
        "name": "Franck Kessié",
        "position": "MF",
        "number": null,
        "club": "Al-Ahli"
      },
      {
        "name": "Amad Diallo",
        "position": "FW",
        "number": null,
        "club": "Manchester United"
      },
      {
        "name": "Evan Ndicka",
        "position": "DF",
        "number": null,
        "club": "Roma"
      },
      {
        "name": "Ibrahim Sangaré",
        "position": "MF",
        "number": null,
        "club": "Nottingham Forest"
      },
      {
        "name": "Nicolas Pépé",
        "position": "FW",
        "number": null,
        "club": "Villarreal"
      }
    ],
    "verified": false
  },
  "EGY": {
    "players": [
      {
        "name": "Mohamed Salah",
        "position": "FW",
        "number": 10,
        "club": "Liverpool"
      },
      {
        "name": "Omar Marmoush",
        "position": "FW",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "Mahmoud Trezeguet",
        "position": "FW",
        "number": null,
        "club": "Al Ahly"
      },
      {
        "name": "Mohamed Abdelmonem",
        "position": "DF",
        "number": null,
        "club": "Nice"
      },
      {
        "name": "Mohamed El Shenawy",
        "position": "GK",
        "number": null,
        "club": "Al Ahly"
      },
      {
        "name": "Ahmed Zizo",
        "position": "MF",
        "number": null,
        "club": "Al Ahly"
      }
    ],
    "verified": false
  },
  "ALG": {
    "players": [
      {
        "name": "Riyad Mahrez",
        "position": "FW",
        "number": 7,
        "club": "Al-Ahli"
      },
      {
        "name": "Amine Gouiri",
        "position": "FW",
        "number": null,
        "club": "Marseille"
      },
      {
        "name": "Mohamed Amine Amoura",
        "position": "FW",
        "number": null,
        "club": "Wolfsburg"
      },
      {
        "name": "Rayan Aït-Nouri",
        "position": "DF",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "Ramy Bensebaini",
        "position": "DF",
        "number": null,
        "club": "Borussia Dortmund"
      },
      {
        "name": "Ibrahim Maza",
        "position": "MF",
        "number": null,
        "club": "Bayer Leverkusen"
      }
    ],
    "verified": false
  },
  "TUN": {
    "players": [
      {
        "name": "Ellyes Skhiri",
        "position": "MF",
        "number": null,
        "club": "Eintracht Frankfurt"
      },
      {
        "name": "Hannibal Mejbri",
        "position": "MF",
        "number": null,
        "club": "Burnley"
      },
      {
        "name": "Montassar Talbi",
        "position": "DF",
        "number": null,
        "club": "Lorient"
      },
      {
        "name": "Youssef Msakni",
        "position": "FW",
        "number": null,
        "club": "Al-Arabi"
      },
      {
        "name": "Rani Khedira",
        "position": "MF",
        "number": null,
        "club": "Union Berlin"
      }
    ],
    "verified": false
  },
  "GHA": {
    "players": [
      {
        "name": "Thomas Partey",
        "position": "MF",
        "number": null,
        "club": "Villarreal"
      },
      {
        "name": "Mohammed Salisu",
        "position": "DF",
        "number": null,
        "club": "AS Monaco"
      },
      {
        "name": "Jordan Ayew",
        "position": "FW",
        "number": null,
        "club": "Leicester City"
      },
      {
        "name": "Antoine Semenyo",
        "position": "FW",
        "number": null,
        "club": "AFC Bournemouth"
      },
      {
        "name": "Iñaki Williams",
        "position": "FW",
        "number": null,
        "club": "Athletic Bilbao"
      }
    ],
    "verified": false
  },
  "CPV": {
    "players": [
      {
        "name": "Ryan Mendes",
        "position": "FW",
        "number": null,
        "club": "Iğdır FK"
      },
      {
        "name": "Vozinha",
        "position": "GK",
        "number": null
      },
      {
        "name": "Jamiro Monteiro",
        "position": "MF",
        "number": null
      },
      {
        "name": "Dailon Livramento",
        "position": "FW",
        "number": null
      }
    ],
    "verified": false
  },
  "RSA": {
    "players": [
      {
        "name": "Teboho Mokoena",
        "position": "MF",
        "number": null,
        "club": "Mamelodi Sundowns"
      },
      {
        "name": "Ronwen Williams",
        "position": "GK",
        "number": null,
        "club": "Mamelodi Sundowns"
      },
      {
        "name": "Lyle Foster",
        "position": "FW",
        "number": null,
        "club": "Burnley"
      },
      {
        "name": "Mbekezeli Mbokazi",
        "position": "DF",
        "number": null,
        "club": "Orlando Pirates"
      },
      {
        "name": "Oswin Appollis",
        "position": "FW",
        "number": null,
        "club": "Orlando Pirates"
      }
    ],
    "verified": false
  },
  "COD": {
    "players": [
      {
        "name": "Yoane Wissa",
        "position": "FW",
        "number": null,
        "club": "Newcastle United"
      },
      {
        "name": "Chancel Mbemba",
        "position": "DF",
        "number": null,
        "club": "Lille"
      },
      {
        "name": "Cédric Bakambu",
        "position": "FW",
        "number": null,
        "club": "Real Betis"
      },
      {
        "name": "Noah Sadiki",
        "position": "MF",
        "number": null,
        "club": "Sunderland"
      }
    ],
    "verified": false
  },
  "JPN": {
    "players": [
      {
        "name": "Takefusa Kubo",
        "position": "FW",
        "number": null,
        "club": "Real Sociedad"
      },
      {
        "name": "Ritsu Dōan",
        "position": "FW",
        "number": null,
        "club": "Eintracht Frankfurt"
      },
      {
        "name": "Ayase Ueda",
        "position": "FW",
        "number": null,
        "club": "Feyenoord"
      },
      {
        "name": "Daichi Kamada",
        "position": "MF",
        "number": null,
        "club": "Crystal Palace"
      },
      {
        "name": "Kō Itakura",
        "position": "DF",
        "number": null,
        "club": "Borussia Mönchengladbach"
      },
      {
        "name": "Wataru Endō",
        "position": "MF",
        "number": null,
        "club": "Liverpool"
      }
    ],
    "verified": false
  },
  "KOR": {
    "players": [
      {
        "name": "Son Heung-min",
        "position": "FW",
        "number": 7,
        "club": "Los Angeles FC"
      },
      {
        "name": "Kim Min-jae",
        "position": "DF",
        "number": null,
        "club": "Bayern Munich"
      },
      {
        "name": "Lee Kang-in",
        "position": "MF",
        "number": null,
        "club": "Paris Saint-Germain"
      },
      {
        "name": "Hwang Hee-chan",
        "position": "FW",
        "number": null,
        "club": "Wolverhampton Wanderers"
      }
    ],
    "verified": false
  },
  "IRN": {
    "players": [
      {
        "name": "Mehdi Taremi",
        "position": "FW",
        "number": null,
        "club": "Olympiacos"
      },
      {
        "name": "Alireza Jahanbakhsh",
        "position": "FW",
        "number": null
      },
      {
        "name": "Mehdi Ghayedi",
        "position": "FW",
        "number": null
      },
      {
        "name": "Saeid Ezatolahi",
        "position": "MF",
        "number": null
      }
    ],
    "verified": false
  },
  "AUS": {
    "players": [
      {
        "name": "Mathew Ryan",
        "position": "GK",
        "number": 1,
        "club": "Levante"
      },
      {
        "name": "Jackson Irvine",
        "position": "MF",
        "number": null,
        "club": "FC St. Pauli"
      },
      {
        "name": "Harry Souttar",
        "position": "DF",
        "number": null,
        "club": "Leicester City"
      },
      {
        "name": "Jordan Bos",
        "position": "DF",
        "number": null,
        "club": "Feyenoord"
      },
      {
        "name": "Nestory Irankunda",
        "position": "FW",
        "number": null
      },
      {
        "name": "Alessandro Circati",
        "position": "DF",
        "number": null,
        "club": "Parma"
      }
    ],
    "verified": false
  },
  "UZB": {
    "players": [
      {
        "name": "Eldor Shomurodov",
        "position": "FW",
        "number": null,
        "club": "Roma"
      },
      {
        "name": "Abdukodir Khusanov",
        "position": "DF",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "Abbosbek Fayzullaev",
        "position": "MF",
        "number": null,
        "club": "CSKA Moscow"
      }
    ],
    "verified": false
  },
  "QAT": {
    "players": [
      {
        "name": "Akram Afif",
        "position": "FW",
        "number": 11,
        "club": "Al Sadd"
      },
      {
        "name": "Almoez Ali",
        "position": "FW",
        "number": null,
        "club": "Al Duhail"
      },
      {
        "name": "Hassan Al-Haydos",
        "position": "MF",
        "number": null,
        "club": "Al Sadd"
      }
    ],
    "verified": false
  },
  "KSA": {
    "players": [
      {
        "name": "Salem Al-Dawsari",
        "position": "FW",
        "number": 10,
        "club": "Al-Hilal"
      },
      {
        "name": "Firas Al-Buraikan",
        "position": "FW",
        "number": null,
        "club": "Al-Ahli"
      },
      {
        "name": "Nawaf Al-Aqidi",
        "position": "GK",
        "number": null
      },
      {
        "name": "Saud Abdulhamid",
        "position": "DF",
        "number": null
      }
    ],
    "verified": false
  },
  "IRQ": {
    "players": [
      {
        "name": "Aymen Hussein",
        "position": "FW",
        "number": null,
        "club": "Al Karma"
      },
      {
        "name": "Ali Al-Hamadi",
        "position": "FW",
        "number": null,
        "club": "Ipswich Town"
      },
      {
        "name": "Zidane Iqbal",
        "position": "MF",
        "number": null,
        "club": "Utrecht"
      },
      {
        "name": "Amir Al-Ammari",
        "position": "MF",
        "number": null
      },
      {
        "name": "Ali Jasim",
        "position": "FW",
        "number": null
      }
    ],
    "verified": false
  },
  "JOR": {
    "players": [
      {
        "name": "Mousa Al-Tamari",
        "position": "FW",
        "number": null,
        "club": "Montpellier"
      },
      {
        "name": "Ali Olwan",
        "position": "FW",
        "number": null
      },
      {
        "name": "Nizar Al-Rashdan",
        "position": "MF",
        "number": null
      },
      {
        "name": "Ehsan Haddad",
        "position": "DF",
        "number": null
      }
    ],
    "verified": false
  },
  "PAN": {
    "players": [
      {
        "name": "Adalberto Carrasquilla",
        "position": "MF",
        "number": null,
        "club": "Pumas UNAM"
      },
      {
        "name": "Aníbal Godoy",
        "position": "MF",
        "number": null
      },
      {
        "name": "Amir Murillo",
        "position": "DF",
        "number": null,
        "club": "Beşiktaş"
      },
      {
        "name": "Ismael Díaz",
        "position": "FW",
        "number": null,
        "club": "Club León"
      },
      {
        "name": "José Fajardo",
        "position": "FW",
        "number": null
      }
    ],
    "verified": false
  },
  "CUW": {
    "players": [
      {
        "name": "Tahith Chong",
        "position": "MF",
        "number": null,
        "club": "Sheffield United"
      },
      {
        "name": "Leandro Bacuna",
        "position": "MF",
        "number": null,
        "club": "Iğdır FK"
      },
      {
        "name": "Juninho Bacuna",
        "position": "MF",
        "number": null
      },
      {
        "name": "Jurgen Locadia",
        "position": "FW",
        "number": null
      },
      {
        "name": "Eloy Room",
        "position": "GK",
        "number": null,
        "club": "Miami FC"
      }
    ],
    "verified": false
  },
  "HAI": {
    "players": [
      {
        "name": "Frantzdy Pierrot",
        "position": "FW",
        "number": null,
        "club": "Çaykur Rizespor"
      },
      {
        "name": "Jean-Ricner Bellegarde",
        "position": "MF",
        "number": null,
        "club": "Wolverhampton Wanderers"
      },
      {
        "name": "Wilson Isidor",
        "position": "FW",
        "number": null,
        "club": "Sunderland"
      },
      {
        "name": "Duckens Nazon",
        "position": "FW",
        "number": null
      },
      {
        "name": "Jean-Kévin Duverne",
        "position": "DF",
        "number": null
      }
    ],
    "verified": false
  },
  "NZL": {
    "players": [
      {
        "name": "Chris Wood",
        "position": "FW",
        "number": null,
        "club": "Nottingham Forest"
      },
      {
        "name": "Liberato Cacace",
        "position": "DF",
        "number": null,
        "club": "Wrexham"
      },
      {
        "name": "Kosta Barbarouses",
        "position": "FW",
        "number": null
      },
      {
        "name": "Max Crocombe",
        "position": "GK",
        "number": null,
        "club": "Millwall"
      },
      {
        "name": "Tommy Smith",
        "position": "DF",
        "number": null,
        "club": "Braintree Town"
      }
    ],
    "verified": false
  },
  "NOR": {
    "players": [
      {
        "name": "Erling Haaland",
        "position": "FW",
        "number": 9,
        "club": "Manchester City"
      },
      {
        "name": "Martin Ødegaard",
        "position": "MF",
        "number": null,
        "club": "Arsenal"
      },
      {
        "name": "Alexander Sørloth",
        "position": "FW",
        "number": null,
        "club": "Atlético Madrid"
      },
      {
        "name": "Antonio Nusa",
        "position": "FW",
        "number": null,
        "club": "RB Leipzig"
      },
      {
        "name": "Kristoffer Ajer",
        "position": "DF",
        "number": null,
        "club": "Brentford"
      }
    ],
    "verified": false
  },
  "SCO": {
    "players": [
      {
        "name": "Scott McTominay",
        "position": "MF",
        "number": null,
        "club": "Napoli"
      },
      {
        "name": "Andrew Robertson",
        "position": "DF",
        "number": null,
        "club": "Liverpool"
      },
      {
        "name": "John McGinn",
        "position": "MF",
        "number": null,
        "club": "Aston Villa"
      },
      {
        "name": "Kieran Tierney",
        "position": "DF",
        "number": null,
        "club": "Celtic"
      },
      {
        "name": "Angus Gunn",
        "position": "GK",
        "number": 1
      }
    ],
    "verified": false
  },
  "AUT": {
    "players": [
      {
        "name": "David Alaba",
        "position": "DF",
        "number": null,
        "club": "Real Madrid"
      },
      {
        "name": "Marko Arnautović",
        "position": "FW",
        "number": null
      },
      {
        "name": "Konrad Laimer",
        "position": "MF",
        "number": null,
        "club": "Bayern Munich"
      },
      {
        "name": "Marcel Sabitzer",
        "position": "MF",
        "number": null,
        "club": "Borussia Dortmund"
      }
    ],
    "verified": false
  },
  "SUI": {
    "players": [
      {
        "name": "Granit Xhaka",
        "position": "MF",
        "number": 10,
        "club": "Sunderland"
      },
      {
        "name": "Manuel Akanji",
        "position": "DF",
        "number": null,
        "club": "Manchester City"
      },
      {
        "name": "Breel Embolo",
        "position": "FW",
        "number": null
      },
      {
        "name": "Ricardo Rodríguez",
        "position": "DF",
        "number": null
      }
    ],
    "verified": false
  },
  "BIH": {
    "players": [
      {
        "name": "Edin Džeko",
        "position": "FW",
        "number": null,
        "club": "Schalke 04"
      },
      {
        "name": "Ermedin Demirović",
        "position": "FW",
        "number": null,
        "club": "Stuttgart"
      },
      {
        "name": "Benjamin Tahirović",
        "position": "MF",
        "number": null
      },
      {
        "name": "Armin Gigović",
        "position": "MF",
        "number": null
      }
    ],
    "verified": false
  },
  "SWE": {
    "players": [
      {
        "name": "Alexander Isak",
        "position": "FW",
        "number": null,
        "club": "Liverpool"
      },
      {
        "name": "Viktor Gyökeres",
        "position": "FW",
        "number": null,
        "club": "Arsenal"
      },
      {
        "name": "Anthony Elanga",
        "position": "FW",
        "number": null,
        "club": "Newcastle United"
      },
      {
        "name": "Benjamin Nygren",
        "position": "FW",
        "number": null,
        "club": "Celtic"
      }
    ],
    "verified": false
  },
  "TUR": {
    "players": [
      {
        "name": "Arda Güler",
        "position": "MF",
        "number": null,
        "club": "Real Madrid"
      },
      {
        "name": "Hakan Çalhanoğlu",
        "position": "MF",
        "number": null,
        "club": "Inter Milan"
      },
      {
        "name": "Kenan Yıldız",
        "position": "FW",
        "number": null,
        "club": "Juventus"
      },
      {
        "name": "Ferdi Kadıoğlu",
        "position": "DF",
        "number": null,
        "club": "Brighton & Hove Albion"
      },
      {
        "name": "Kerem Aktürkoğlu",
        "position": "FW",
        "number": null,
        "club": "Fenerbahçe"
      }
    ],
    "verified": false
  },
  "CZE": {
    "players": [
      {
        "name": "Patrik Schick",
        "position": "FW",
        "number": null,
        "club": "Bayer Leverkusen"
      },
      {
        "name": "Tomáš Souček",
        "position": "MF",
        "number": null,
        "club": "West Ham United"
      },
      {
        "name": "Adam Hložek",
        "position": "FW",
        "number": null,
        "club": "Hoffenheim"
      }
    ],
    "verified": false
  }
}
