/**
 * AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.
 * Verified 2026 World Cup snapshot as of 2026-06-25.
 */
import type { Team } from '@/domain/types'

export const TEAMS: Team[] = [
  {
    "code": "MEX",
    "name": "Mexico",
    "nameTC": "墨西哥",
    "group": "A",
    "color": "#006847",
    "color2": "#CE1126",
    "symbol": "Golden eagle",
    "host": true
  },
  {
    "code": "RSA",
    "name": "South Africa",
    "nameTC": "南非",
    "group": "A",
    "color": "#007749",
    "color2": "#FFB81C",
    "symbol": "Springbok / Protea flower"
  },
  {
    "code": "KOR",
    "name": "South Korea",
    "nameTC": "南韓",
    "group": "A",
    "color": "#CD2E3A",
    "color2": "#0047A0",
    "symbol": "Tiger"
  },
  {
    "code": "CZE",
    "name": "Czechia",
    "nameTC": "捷克",
    "group": "A",
    "color": "#D7141A",
    "color2": "#11457E",
    "symbol": "Linden leaf"
  },
  {
    "code": "CAN",
    "name": "Canada",
    "nameTC": "加拿大",
    "group": "B",
    "color": "#D52B1E",
    "color2": "#FFFFFF",
    "symbol": "Maple leaf",
    "host": true
  },
  {
    "code": "BIH",
    "name": "Bosnia and Herzegovina",
    "nameTC": "波士尼亞",
    "group": "B",
    "color": "#002395",
    "color2": "#FFCC00",
    "symbol": "Golden lily (Lilium bosniacum)"
  },
  {
    "code": "QAT",
    "name": "Qatar",
    "nameTC": "卡達",
    "group": "B",
    "color": "#8A1538",
    "color2": "#FFFFFF",
    "symbol": "Oryx (Arabian oryx)"
  },
  {
    "code": "SUI",
    "name": "Switzerland",
    "nameTC": "瑞士",
    "group": "B",
    "color": "#D52B1E",
    "color2": "#FFFFFF",
    "symbol": "Edelweiss flower"
  },
  {
    "code": "BRA",
    "name": "Brazil",
    "nameTC": "巴西",
    "group": "C",
    "color": "#FFDF00",
    "color2": "#009C3B",
    "symbol": "Toucan"
  },
  {
    "code": "MAR",
    "name": "Morocco",
    "nameTC": "摩洛哥",
    "group": "C",
    "color": "#C1272D",
    "color2": "#006233",
    "symbol": "Lion (Atlas lion)"
  },
  {
    "code": "HAI",
    "name": "Haiti",
    "nameTC": "海地",
    "group": "C",
    "color": "#00209F",
    "color2": "#D21034",
    "symbol": "Hispaniolan trogon"
  },
  {
    "code": "SCO",
    "name": "Scotland",
    "nameTC": "蘇格蘭",
    "group": "C",
    "color": "#0065BF",
    "color2": "#FFFFFF",
    "symbol": "Thistle"
  },
  {
    "code": "USA",
    "name": "United States",
    "nameTC": "美國",
    "group": "D",
    "color": "#3C3B6E",
    "color2": "#B22234",
    "symbol": "Bald eagle",
    "host": true
  },
  {
    "code": "PAR",
    "name": "Paraguay",
    "nameTC": "巴拉圭",
    "group": "D",
    "color": "#D52B1E",
    "color2": "#0038A8",
    "symbol": "Bellbird (campana)"
  },
  {
    "code": "AUS",
    "name": "Australia",
    "nameTC": "澳洲",
    "group": "D",
    "color": "#00843D",
    "color2": "#FFCD00",
    "symbol": "Kangaroo"
  },
  {
    "code": "TUR",
    "name": "Türkiye",
    "nameTC": "土耳其",
    "group": "D",
    "color": "#E30A17",
    "color2": "#FFFFFF",
    "symbol": "Crescent moon and star / tulip"
  },
  {
    "code": "GER",
    "name": "Germany",
    "nameTC": "德國",
    "group": "E",
    "color": "#000000",
    "color2": "#DD0000",
    "symbol": "Eagle (Bundesadler)"
  },
  {
    "code": "CUW",
    "name": "Curaçao",
    "nameTC": "古拉索",
    "group": "E",
    "color": "#002B7F",
    "color2": "#F9E814",
    "symbol": "Flamingo"
  },
  {
    "code": "CIV",
    "name": "Côte d'Ivoire",
    "nameTC": "象牙海岸",
    "group": "E",
    "color": "#FF8200",
    "color2": "#009E60",
    "symbol": "Elephant"
  },
  {
    "code": "ECU",
    "name": "Ecuador",
    "nameTC": "厄瓜多",
    "group": "E",
    "color": "#FFDD00",
    "color2": "#034EA2",
    "symbol": "Andean condor"
  },
  {
    "code": "NED",
    "name": "Netherlands",
    "nameTC": "荷蘭",
    "group": "F",
    "color": "#FF6200",
    "color2": "#FFFFFF",
    "symbol": "Tulip"
  },
  {
    "code": "JPN",
    "name": "Japan",
    "nameTC": "日本",
    "group": "F",
    "color": "#BC002D",
    "color2": "#FFFFFF",
    "symbol": "Red-crowned crane"
  },
  {
    "code": "SWE",
    "name": "Sweden",
    "nameTC": "瑞典",
    "group": "F",
    "color": "#006AA7",
    "color2": "#FECC00",
    "symbol": "Elk / moose"
  },
  {
    "code": "TUN",
    "name": "Tunisia",
    "nameTC": "突尼西亞",
    "group": "F",
    "color": "#E70013",
    "color2": "#FFFFFF",
    "symbol": "Eagle of Carthage"
  },
  {
    "code": "BEL",
    "name": "Belgium",
    "nameTC": "比利時",
    "group": "G",
    "color": "#E30613",
    "color2": "#FAE042",
    "symbol": "Lion (Flemish lion)"
  },
  {
    "code": "EGY",
    "name": "Egypt",
    "nameTC": "埃及",
    "group": "G",
    "color": "#CE1126",
    "color2": "#000000",
    "symbol": "Lotus flower"
  },
  {
    "code": "IRN",
    "name": "Iran",
    "nameTC": "伊朗",
    "group": "G",
    "color": "#239F40",
    "color2": "#DA0000",
    "symbol": "Cheetah (Asiatic cheetah)"
  },
  {
    "code": "NZL",
    "name": "New Zealand",
    "nameTC": "紐西蘭",
    "group": "G",
    "color": "#000000",
    "color2": "#FFFFFF",
    "symbol": "Kiwi bird"
  },
  {
    "code": "ESP",
    "name": "Spain",
    "nameTC": "西班牙",
    "group": "H",
    "color": "#C60B1E",
    "color2": "#FFC400",
    "symbol": "Bull (gentle silhouette)"
  },
  {
    "code": "CPV",
    "name": "Cabo Verde",
    "nameTC": "維德角",
    "group": "H",
    "color": "#003893",
    "color2": "#CF2027",
    "symbol": "Cory's shearwater (seabird)"
  },
  {
    "code": "KSA",
    "name": "Saudi Arabia",
    "nameTC": "沙烏地阿拉伯",
    "group": "H",
    "color": "#006C35",
    "color2": "#FFFFFF",
    "symbol": "Date palm"
  },
  {
    "code": "URU",
    "name": "Uruguay",
    "nameTC": "烏拉圭",
    "group": "H",
    "color": "#7FB3D5",
    "color2": "#FFFFFF",
    "symbol": "Sun of May"
  },
  {
    "code": "FRA",
    "name": "France",
    "nameTC": "法國",
    "group": "I",
    "color": "#0055A4",
    "color2": "#EF4135",
    "symbol": "Rooster (Gallic rooster)"
  },
  {
    "code": "SEN",
    "name": "Senegal",
    "nameTC": "塞內加爾",
    "group": "I",
    "color": "#00853F",
    "color2": "#FDEF42",
    "symbol": "Lion (Lion of Teranga)"
  },
  {
    "code": "IRQ",
    "name": "Iraq",
    "nameTC": "伊拉克",
    "group": "I",
    "color": "#007A3D",
    "color2": "#CE1126",
    "symbol": "Date palm"
  },
  {
    "code": "NOR",
    "name": "Norway",
    "nameTC": "挪威",
    "group": "I",
    "color": "#BA0C2F",
    "color2": "#00205B",
    "symbol": "Elk / moose"
  },
  {
    "code": "ARG",
    "name": "Argentina",
    "nameTC": "阿根廷",
    "group": "J",
    "color": "#75AADB",
    "color2": "#FFFFFF",
    "symbol": "Sun of May"
  },
  {
    "code": "ALG",
    "name": "Algeria",
    "nameTC": "阿爾及利亞",
    "group": "J",
    "color": "#006233",
    "color2": "#FFFFFF",
    "symbol": "Fennec fox"
  },
  {
    "code": "AUT",
    "name": "Austria",
    "nameTC": "奧地利",
    "group": "J",
    "color": "#ED2939",
    "color2": "#FFFFFF",
    "symbol": "Edelweiss flower"
  },
  {
    "code": "JOR",
    "name": "Jordan",
    "nameTC": "約旦",
    "group": "J",
    "color": "#007A3D",
    "color2": "#CE1126",
    "symbol": "Oryx (Arabian oryx)"
  },
  {
    "code": "POR",
    "name": "Portugal",
    "nameTC": "葡萄牙",
    "group": "K",
    "color": "#FF0000",
    "color2": "#006600",
    "symbol": "Rooster of Barcelos"
  },
  {
    "code": "COD",
    "name": "DR Congo",
    "nameTC": "剛果民主共和國",
    "group": "K",
    "color": "#007FFF",
    "color2": "#F7D618",
    "symbol": "Leopard"
  },
  {
    "code": "UZB",
    "name": "Uzbekistan",
    "nameTC": "烏茲別克",
    "group": "K",
    "color": "#1EB53A",
    "color2": "#0099B5",
    "symbol": "Khumo (Huma bird)"
  },
  {
    "code": "COL",
    "name": "Colombia",
    "nameTC": "哥倫比亞",
    "group": "K",
    "color": "#FCD116",
    "color2": "#003893",
    "symbol": "Andean condor"
  },
  {
    "code": "ENG",
    "name": "England",
    "nameTC": "英格蘭",
    "group": "L",
    "color": "#FFFFFF",
    "color2": "#CE1124",
    "symbol": "Three lions / red rose"
  },
  {
    "code": "CRO",
    "name": "Croatia",
    "nameTC": "克羅埃西亞",
    "group": "L",
    "color": "#FF0000",
    "color2": "#FFFFFF",
    "symbol": "Red-and-white checkerboard (šahovnica)"
  },
  {
    "code": "GHA",
    "name": "Ghana",
    "nameTC": "迦納",
    "group": "L",
    "color": "#006B3F",
    "color2": "#FCD116",
    "symbol": "Black star"
  },
  {
    "code": "PAN",
    "name": "Panama",
    "nameTC": "巴拿馬",
    "group": "L",
    "color": "#005293",
    "color2": "#DA121A",
    "symbol": "Harpy eagle"
  }
]

export const teamByCode: Record<string, Team> = Object.fromEntries(
  TEAMS.map((t) => [t.code, t]),
)

export const GROUP_IDS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L'] as const
